In [11]:
import numpy as np

In [2]:
states = ('Healthy','Fever')

observations=('normal','cold','dizzy')

start_probability = {'Healthy':0.6,'Fever':0.4}

transition_probability = {
    'Healthy': {'Healthy': 0.7, 'Fever': 0.3},
    'Fever': {'Healthy': 0.4, 'Fever': 0.6},
}

emission_probability={
    'Healthy':{'normal':0.5,'cold':0.4,'dizzy':0.1},
    'Fever':{'normal':0.1,'cold':0.3,'dizzy':0.6},
}

In [12]:
#generate observation and state sequence randomly in length T
def simulate(T):
    def draw_from(probs):
        return np.where(np.random.multinomial(1,probs)==1)[0][0]
    
    observations = np.zeros(T, dtype=int)#initialize ob
    states = np.zeros(T, dtype=int)#initialize states
    states[0] = draw_from(pi) #first state
    observations[0] = draw_from(B[states[0],:]) #first ob using B
    
    for t in range(1,T):#generate sequence
        states[t] = draw_from(A[states[t-1],:])
        observations[t] = draw_from(B[states[t],:])
    return observations, states

In [13]:
def generate_index_map(labels):
    id2label = {}
    label2id = {}
    i=0
    for l in labels:
        id2label[i] = l
        label2id[l] = i
        i+=1
    return id2label, label2id


In [23]:
states_id2label, states_label2id = generate_index_map(states)
observations_id2label, observations_label2id = generate_index_map(observations)
print(states_id2label, states_label2id)
print(observations_id2label, observations_label2id)

{0: 'Healthy', 1: 'Fever'} {'Healthy': 0, 'Fever': 1}
{0: 'normal', 1: 'cold', 2: 'dizzy'} {'normal': 0, 'cold': 1, 'dizzy': 2}


In [16]:
def convert_map_to_vector(map_,label2id):
    #convert prob from dict to 1-d array
    v = np.zeros(len(map_), dtype=float)
    for e in map_:
        v[label2id[e]]= map_[e]
    return v

def convert_map_to_matrix(map_,label2id1,label2id2):
    #convert prob from dict to matrix
    m = np.zeros((len(label2id1),len(label2id2)),dtype=float)
    for line in map_:
        for col in map_[line]:
            m[label2id1[line]][label2id2[col]] = map_[line][col]
    return m

In [19]:
A = convert_map_to_matrix(transition_probability, states_label2id, states_label2id)
print(A)

B = convert_map_to_matrix(emission_probability, states_label2id, observations_label2id)
print(B)

pi = convert_map_to_vector(start_probability, states_label2id)
print(pi)

[[0.7 0.3]
 [0.4 0.6]]
[[0.5 0.4 0.1]
 [0.1 0.3 0.6]]
[0.6 0.4]


In [24]:
#generate simulate data
observations_data, states_data = simulate(10)
print(observations_data)
print(states_data)

print("States of patients:", [states_id2label[index] for index in states_data])
print("Observations of patients:", [observations_id2label[index] for index in observations_data])

[2 0 0 0 2 2 2 2 2 1]
[1 0 0 0 1 1 1 1 0 0]
States of patients: ['Fever', 'Healthy', 'Healthy', 'Healthy', 'Fever', 'Fever', 'Fever', 'Fever', 'Healthy', 'Healthy']
Observations of patients: ['dizzy', 'normal', 'normal', 'normal', 'dizzy', 'dizzy', 'dizzy', 'dizzy', 'dizzy', 'cold']


In [ ]:
def forward(obs_seq):
    #forward algorithm
    N = A.shape[0] #number of rows in A,which means state number
    T = len(obs_seq)
    
    #F stores forward probability
    F = np.zeros((N,T))
    F[:,0] = pi * B[:, obs_seq[0]]
    
    for t in range(1,T):
        for n in range(N):
            F[n,t]
    